---
- name: restart metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    daemon_reload: yes
  when: metricbeat_service_state != 'stopped' and not metricbeat_service_output.changed
